site_name: spacypdfreader
site_description: PDF to spaCy text extraction.
repo_url: https://github.com/samedwardes/spacypdfreader
repo_name: 'samedwardes/spacypdfreader'
edit_uri: ''

theme:
  name: material
  icon:
    logo: fontawesome/solid/user-astronaut
  favicon: fontawesome/solid/user-astronaut
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      watch:
        - spacypdfreader
      handlers:
        python:
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.modules["spacy"] = mock()
            - sys.modules["spacy.tokens"] = mock()
            - sys.modules["rich.console"] = mock()
            - sys.modules["rich.progress"] = mock()
            - sys.modules["pdfminer"] = mock()
            - sys.modules["pdfminer.pdfparser"] = mock()
            - sys.modules["pdfminer.pdfpage"] = mock()
            - sys.modules["pdfminer.pdfdocument"] = mock()
            - sys.modules["pdfminer.high_level"] = mock()
            - sys.modules["pytesseract"] = mock()
            - sys.modules["PIL"] = mock()
            - sys.modules["pdf2image"] = mock()
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_category_heading: false
            show_root_heading: true
            show_signature_annotations: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/samedwardes/spacypdfreader
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/therealsamlam
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samedwardes

nav:
  - Home: 'index.md'
  - parsers.md
  - changelog.md
  - contributing.md
  - API reference:
    - api/spacy-extensions.md
    - api/spacypdfreader.spacypdfreader.md
    - api/spacypdfreader.parsers.md