site_name: spacypdfreader
site_description: PDF to spaCy text extraction.
site_url: https://samedwardes.github.io/spacypdfreader/
repo_url: https://github.com/samedwardes/spacypdfreader
edit_uri: ''

theme:
  name: material
  icon:
    logo: fontawesome/solid/user-astronaut
  favicon: fontawesome/solid/user-astronaut
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - include-markdown
  - mkdocstrings:
      watch:
        - spacypdfreader
      handlers:
        python:
          rendering:
            show_root_heading: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/samedwardes/spacypdfreader
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/therealsamlam
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samedwardes

nav:
  - Home: 'index.md'
  - parsers.md
  - changelog.md
  - contributing.md
  - API reference:
    - api/spacy-extensions.md
    - api/spacypdfreader.spacypdfreader.md
    - api/spacypdfreader.parsers.md