[build]
publish = "site"
command = """
pip3 install -q poetry &&
poetry export --dev --without-hashes | grep mkdocs > requirements.txt &&
pip3 install -r requirements.txt &&
poetry run pydoc-markdownrm build -d site
"""