[build]
publish = "site"
command = """
pip install -q poetry &&
poetry export --dev --without-hashes --output requirements.txt
pip install -r requirements.txt &&
poetry run pydoc-markdownrm build -d site
"""