name: ci 
on:
  push:
    branches: 
      - master
      - main
      - mkdocs-website
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry export --without-hashes --output requirements.txt
      - run: pip install wheel
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
